/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MembersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClubsController_findMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs/{clubId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClubsController_findMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs/{clubId}/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BooksController_list"];
        put?: never;
        post: operations["BooksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BooksController_detail"];
        put?: never;
        post?: never;
        delete: operations["BooksController_remove"];
        options?: never;
        head?: never;
        patch: operations["BooksController_update"];
        trace?: never;
    };
    "/api/comments/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CommentsController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CommentsController_list"];
        put?: never;
        post: operations["CommentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CommentsController_remove"];
        options?: never;
        head?: never;
        patch: operations["CommentsController_update"];
        trace?: never;
    };
    "/api/comments/{commentId}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CommentsController_toggleLike"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs/{clubId}/orders/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_estimate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs/{clubId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrdersController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminOrdersController_listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminOrdersController_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{orderId}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminOrdersController_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/bulk-transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminOrdersController_bulkTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{orderId}/production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminOrdersController_checkProduction"];
        put?: never;
        post: operations["AdminOrdersController_dispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{orderId}/vendor-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminOrdersController_receiveVendorEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminClubsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clubs/{clubId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminClubsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clubs/{clubId}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminClubsController_updateNote"];
        trace?: never;
    };
    "/api/admin/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminMembersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminMembersController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/members/{memberId}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminMembersController_updateNote"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MemberAccountClubResponse: {
            /** @enum {string} */
            role: "LEADER" | "MEMBER";
            publicId: string;
            name: string;
        };
        MemberAccountResponse: {
            publicId: string;
            name: string;
            avatarEmoji: string;
            color: string;
            clubs: components["schemas"]["MemberAccountClubResponse"][];
        };
        MyClubResponse: {
            /** @enum {string} */
            myRole: "LEADER" | "MEMBER";
            publicId: string;
            name: string;
            description: string;
            memberCount: number;
            /** Format: date-time */
            joinedAt: string;
        };
        ClubMemberResponse: {
            /** @enum {string} */
            role: "LEADER" | "MEMBER";
            publicId: string;
            name: string;
            avatarEmoji: string;
            color: string;
            /** Format: date-time */
            joinedAt: string;
        };
        MemberSummaryResponse: {
            publicId: string;
            name: string;
            avatarEmoji: string;
            color: string;
        };
        BookResponse: {
            /** @enum {string} */
            status: "UPCOMING" | "READING" | "DONE";
            publicId: string;
            title: string;
            author: string;
            publisher: string | null;
            coverColor: string;
            coverEmoji: string;
            /** Format: date-time */
            meetingDate: string | null;
            /** Format: date-time */
            periodFrom: string | null;
            /** Format: date-time */
            periodTo: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            participants: components["schemas"]["MemberSummaryResponse"][];
            commentCount: number;
        };
        PageMetaResponse: {
            page: number;
            limit: number;
            totalCount: number;
            hasNext: boolean;
        };
        PaginatedBooksResponse: {
            items: components["schemas"]["BookResponse"][];
            meta: components["schemas"]["PageMetaResponse"];
        };
        CreateBookDto: {
            title: string;
            author: string;
            publisher?: string | null;
            coverColor: string;
            coverEmoji: string;
            /** @enum {string} */
            status?: "UPCOMING" | "READING" | "DONE";
            meetingDate?: string | null;
            periodFrom?: string | null;
            periodTo?: string | null;
            participantIds?: string[];
        };
        UpdateBookDto: {
            title?: string;
            author?: string;
            publisher?: string | null;
            coverColor?: string;
            coverEmoji?: string;
            /** @enum {string} */
            status?: "UPCOMING" | "READING" | "DONE";
            meetingDate?: string | null;
            periodFrom?: string | null;
            periodTo?: string | null;
            participantIds?: string[];
        };
        DeletedResponse: {
            publicId: string;
            deleted: boolean;
        };
        MyCommentBookResponse: {
            publicId: string;
            title: string;
            coverColor: string;
            coverEmoji: string;
        };
        MyCommentClubResponse: {
            publicId: string;
            name: string;
        };
        MyCommentResponse: {
            publicId: string;
            page: number | null;
            quote: string | null;
            content: string;
            /** Format: date-time */
            createdAt: string;
            isEdited: boolean;
            likeCount: number;
            book: components["schemas"]["MyCommentBookResponse"];
            club: components["schemas"]["MyCommentClubResponse"];
        };
        PaginatedMyCommentsResponse: {
            items: components["schemas"]["MyCommentResponse"][];
            meta: components["schemas"]["PageMetaResponse"];
        };
        CommentResponse: {
            publicId: string;
            deleted: boolean;
            member: components["schemas"]["MemberSummaryResponse"] | null;
            page: number | null;
            quote: string | null;
            content: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            isEdited: boolean;
            likeCount: number;
            likedByMe: boolean;
        };
        CommentThreadResponse: {
            replies: components["schemas"]["CommentResponse"][];
            publicId: string;
            deleted: boolean;
            member: components["schemas"]["MemberSummaryResponse"] | null;
            page: number | null;
            quote: string | null;
            content: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            isEdited: boolean;
            likeCount: number;
            likedByMe: boolean;
        };
        PaginatedCommentsResponse: {
            items: components["schemas"]["CommentThreadResponse"][];
            meta: components["schemas"]["PageMetaResponse"];
        };
        CreateCommentDto: {
            content: string;
            page?: number | null;
            quote?: string | null;
            parentId?: string;
        };
        UpdateCommentDto: {
            content?: string;
            page?: number | null;
            quote?: string | null;
        };
        CommentLikeResponse: {
            liked: boolean;
            likeCount: number;
        };
        EstimateOrderDto: {
            bookIds: string[];
            copies: number;
        };
        PageBreakdownResponse: {
            frontMatter: number;
            bookHeaders: number;
            comments: number;
            backMatter: number;
        };
        BookSpecOptionResponse: {
            /** @enum {string} */
            coverType: "SOFTCOVER" | "HARDCOVER";
            /** @enum {string} */
            bindingType: "PUR" | "LAYFLAT";
            /** @enum {string|null} */
            ineligibleReason: "PAGE_MIN" | "PAGE_MAX" | "PAGE_INCREMENT" | null;
            requiredValue: number | null;
            bookSpecUid: string;
            name: string;
            innerTrimWidthMm: number;
            innerTrimHeightMm: number;
            pageMin: number;
            pageMax: number;
            pageIncrement: number;
            priceBase: number;
            pricePerIncrement: number;
            description: string;
            eligible: boolean;
            unitPrice: number;
            productAmount: number;
            shippingFee: number;
            totalAmount: number;
        };
        DeliveryEstimateResponse: {
            /** Format: date-time */
            earliest: string;
            /** Format: date-time */
            latest: string;
        };
        OrderEstimateResponse: {
            pageCount: number;
            blankPages: number;
            breakdown: components["schemas"]["PageBreakdownResponse"];
            printable: boolean;
            specs: components["schemas"]["BookSpecOptionResponse"][];
            shippingFee: number;
            delivery: components["schemas"]["DeliveryEstimateResponse"];
        };
        CreateOrderDto: {
            title: string;
            copies: number;
            bookIds: string[];
            bookSpecUid: string;
            coverColor: string;
            coverEmoji: string;
        };
        OrderBookSpecResponse: {
            /** @enum {string|null} */
            coverType: "SOFTCOVER" | "HARDCOVER" | null;
            /** @enum {string|null} */
            bindingType: "PUR" | "LAYFLAT" | null;
            innerTrimWidthMm: number | null;
            innerTrimHeightMm: number | null;
            bookSpecUid: string;
            name: string;
        };
        OrderClubSummaryResponse: {
            publicId: string;
            name: string;
        };
        OrderBookSummaryResponse: {
            publicId: string;
            title: string;
            author: string;
            coverColor: string;
            coverEmoji: string;
        };
        OrderHistoryResponse: {
            /** @enum {string|null} */
            fromStatus: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED" | null;
            /** @enum {string} */
            toStatus: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            /** @enum {string} */
            actor: "USER" | "ADMIN" | "VENDOR";
            /** @enum {string|null} */
            reason: "PRINT_DEFECT" | "BINDING_DEFECT" | "DAMAGED_IN_TRANSIT" | "WRONG_CONTENT" | "OTHER" | null;
            /** Format: date-time */
            changedAt: string;
            reasonDetail: string | null;
            adminNote: string | null;
        };
        OrderResponse: {
            /** @enum {string} */
            status: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            trackingCarrier: string | null;
            trackingNumber: string | null;
            publicId: string;
            title: string;
            copies: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            statusChangedAt: string;
            bookSpec: components["schemas"]["OrderBookSpecResponse"];
            coverColor: string;
            coverEmoji: string;
            pageCount: number;
            unitPrice: number;
            productAmount: number;
            shippingFee: number;
            totalAmount: number;
            club: components["schemas"]["OrderClubSummaryResponse"];
            member: components["schemas"]["MemberSummaryResponse"];
            books: components["schemas"]["OrderBookSummaryResponse"][];
            history: components["schemas"]["OrderHistoryResponse"][];
        };
        PaginatedOrdersResponse: {
            items: components["schemas"]["OrderResponse"][];
            meta: components["schemas"]["PageMetaResponse"];
        };
        TransitionOrderDto: {
            /** @enum {string} */
            toStatus: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            /** @enum {string} */
            reason?: "PRINT_DEFECT" | "BINDING_DEFECT" | "DAMAGED_IN_TRANSIT" | "WRONG_CONTENT" | "OTHER";
            reasonDetail?: string;
        };
        AdminOrderResponse: {
            /** @enum {string} */
            status: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            trackingCarrier: string | null;
            trackingNumber: string | null;
            nextStatuses: ("RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED")[];
            vendorOrderUid: string | null;
            vendorStatus: string | null;
            vendorStatusDisplay: string | null;
            /** Format: date-time */
            vendorStatusAt: string | null;
            publicId: string;
            title: string;
            copies: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            statusChangedAt: string;
            bookSpec: components["schemas"]["OrderBookSpecResponse"];
            coverColor: string;
            coverEmoji: string;
            pageCount: number;
            unitPrice: number;
            productAmount: number;
            shippingFee: number;
            totalAmount: number;
            club: components["schemas"]["OrderClubSummaryResponse"];
            member: components["schemas"]["MemberSummaryResponse"];
            books: components["schemas"]["OrderBookSummaryResponse"][];
            history: components["schemas"]["OrderHistoryResponse"][];
        };
        PaginatedAdminOrdersResponse: {
            items: components["schemas"]["AdminOrderResponse"][];
            meta: components["schemas"]["PageMetaResponse"];
        };
        AdminTransitionOrderDto: {
            /** @enum {string} */
            toStatus: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            adminNote?: string;
        };
        AdminBulkTransitionDto: {
            /** @enum {string} */
            toStatus: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            adminNote?: string;
            orderIds: string[];
        };
        VendorEventLogResponse: {
            detail: string | null;
            event: string;
            vendorStatus: string;
            vendorStatusDisplay: string;
            /** Format: date-time */
            receivedAt: string;
        };
        AdminProductionCheckResponse: {
            pageMin: number | null;
            pageMax: number | null;
            /** @enum {string|null} */
            ineligibleReason: "PAGE_MIN" | "PAGE_MAX" | "PAGE_INCREMENT" | null;
            requiredValue: number | null;
            vendorOrderUid: string | null;
            vendorStatus: string | null;
            vendorStatusDisplay: string | null;
            /** Format: date-time */
            vendorStatusAt: string | null;
            trackingCarrier: string | null;
            trackingNumber: string | null;
            bookSpecUid: string;
            specName: string;
            orderedPageCount: number;
            currentPageCount: number;
            eligible: boolean;
            canDispatch: boolean;
            events: components["schemas"]["VendorEventLogResponse"][];
        };
        AdminDispatchDto: {
            adminNote?: string;
        };
        AdminVendorEventDto: {
            /** @enum {string} */
            event: "production.confirmed" | "production.started" | "production.completed" | "shipping.departed" | "shipping.delivered";
        };
        AdminClubResponse: {
            publicId: string;
            name: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            memberCount: number;
            bookCount: number;
            orderCount: number;
            hasAdminNote: boolean;
        };
        AdminClubMemberResponse: {
            /** @enum {string} */
            role: "LEADER" | "MEMBER";
            publicId: string;
            name: string;
            avatarEmoji: string;
            color: string;
            /** Format: date-time */
            joinedAt: string;
        };
        AdminClubOrderResponse: {
            /** @enum {string} */
            status: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            publicId: string;
            title: string;
            copies: number;
            /** Format: date-time */
            createdAt: string;
            memberName: string;
        };
        AdminClubDetailResponse: {
            adminNote: string | null;
            publicId: string;
            name: string;
            description: string;
            inviteCode: string;
            /** Format: date-time */
            createdAt: string;
            memberCount: number;
            bookCount: number;
            orderCount: number;
            members: components["schemas"]["AdminClubMemberResponse"][];
            recentOrders: components["schemas"]["AdminClubOrderResponse"][];
        };
        AdminNoteDto: {
            note?: string;
        };
        AdminNoteResponse: {
            adminNote: string | null;
        };
        AdminMemberClubResponse: {
            /** @enum {string} */
            role: "LEADER" | "MEMBER";
            publicId: string;
            name: string;
            /** Format: date-time */
            joinedAt: string;
        };
        AdminMemberResponse: {
            publicId: string;
            name: string;
            avatarEmoji: string;
            color: string;
            /** Format: date-time */
            createdAt: string;
            clubs: components["schemas"]["AdminMemberClubResponse"][];
            commentCount: number;
            orderCount: number;
            hasAdminNote: boolean;
        };
        PaginatedAdminMembersResponse: {
            items: components["schemas"]["AdminMemberResponse"][];
            meta: components["schemas"]["PageMetaResponse"];
        };
        AdminMemberOrderResponse: {
            /** @enum {string} */
            status: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
            publicId: string;
            title: string;
            copies: number;
            /** Format: date-time */
            createdAt: string;
            clubName: string;
        };
        AdminMemberDetailResponse: {
            adminNote: string | null;
            publicId: string;
            name: string;
            avatarEmoji: string;
            color: string;
            /** Format: date-time */
            createdAt: string;
            clubs: components["schemas"]["AdminMemberClubResponse"][];
            commentCount: number;
            likeCount: number;
            orderCount: number;
            recentOrders: components["schemas"]["AdminMemberOrderResponse"][];
        };
        ApiErrorItemResponse: {
            /** @enum {string} */
            code: "INTERNAL_ERROR" | "MEMBER_HEADER_REQUIRED" | "MEMBER_NOT_FOUND" | "ADMIN_NOTE_MAX" | "COMMON_INVALID_INPUT" | "UNKNOWN_FIELD" | "PAGE_INVALID" | "LIMIT_INVALID" | "CLUB_NOT_FOUND" | "CLUB_MEMBER_ONLY" | "LEADER_ONLY" | "BOOK_NOT_FOUND" | "BOOK_TITLE_REQUIRED" | "BOOK_AUTHOR_REQUIRED" | "BOOK_COVER_COLOR_FORMAT" | "BOOK_TITLE_MAX" | "BOOK_AUTHOR_MAX" | "BOOK_PUBLISHER_MAX" | "BOOK_COVER_EMOJI_INVALID" | "BOOK_STATUS_INVALID" | "BOOK_DATE_INVALID" | "BOOK_PERIOD_INVALID" | "BOOK_PARTICIPANT_NOT_IN_CLUB" | "ORDER_NOT_FOUND" | "ORDER_TITLE_REQUIRED" | "ORDER_COPIES_MIN" | "ORDER_COPIES_MAX" | "ORDER_TITLE_MAX" | "ORDER_BOOKS_REQUIRED" | "ORDER_BOOK_INVALID" | "ORDER_BOOK_NOT_DONE" | "ORDER_INVALID_TRANSITION" | "ORDER_ADMIN_ONLY_TRANSITION" | "ORDER_ORDERER_ONLY" | "ORDER_REASON_REQUIRED" | "ORDER_REASON_INVALID" | "ORDER_REASON_DETAIL_REQUIRED" | "ORDER_REASON_DETAIL_MIN" | "ORDER_REASON_DETAIL_MAX" | "ORDER_STATUS_INVALID" | "ORDER_ADMIN_NOTE_MAX" | "ORDER_BULK_EMPTY" | "ORDER_BULK_TOO_MANY" | "ORDER_COVER_COLOR_FORMAT" | "ORDER_COVER_EMOJI_INVALID" | "PRINT_SPEC_NOT_FOUND" | "PRINT_PAGE_MIN" | "PRINT_PAGE_MAX" | "PRINT_PAGE_INCREMENT" | "PRINT_NO_ELIGIBLE_SPEC" | "PRINT_ALREADY_ORDERED" | "PRINT_NOT_ORDERED" | "PRINT_VENDOR_REJECTED" | "PRINT_VENDOR_UNAVAILABLE" | "PRINT_VENDOR_RATE_LIMITED" | "PRINT_INSUFFICIENT_CREDIT" | "PRINT_WEBHOOK_EVENT_INVALID" | "COMMENT_NOT_FOUND" | "COMMENT_AUTHOR_ONLY" | "COMMENT_CONTENT_REQUIRED" | "COMMENT_CONTENT_TOO_LONG" | "COMMENT_PAGE_MIN" | "COMMENT_QUOTE_TOO_LONG" | "REPLY_TARGET_NOT_FOUND" | "REPLY_TO_OTHER_BOOK" | "REPLY_DEPTH_EXCEEDED" | "REPLY_TO_DELETED" | "NOT_FOUND" | "UNKNOWN";
            message: string;
        };
        ApiErrorResponse: {
            statusCode: number;
            errors: components["schemas"]["ApiErrorItemResponse"][];
            timestamp: string;
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberAccountResponse"][];
                };
            };
        };
    };
    ClubsController_findMine: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — /clubs/mine에는 필수 (D-017) */
                "X-Member-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyClubResponse"][];
                };
            };
        };
    };
    ClubsController_findMembers: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — /clubs/mine에는 필수 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubMemberResponse"][];
                };
            };
        };
    };
    BooksController_list: {
        parameters: {
            query?: {
                status?: "UPCOMING" | "READING" | "DONE";
                page?: number;
                limit?: number;
            };
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBooksResponse"];
                };
            };
        };
    };
    BooksController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    BooksController_detail: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    BooksController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedResponse"];
                };
            };
        };
    };
    BooksController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    CommentsController_listMine: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMyCommentsResponse"];
                };
            };
        };
    };
    CommentsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCommentsResponse"];
                };
            };
        };
    };
    CommentsController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    CommentsController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedResponse"];
                };
            };
        };
    };
    CommentsController_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    CommentsController_toggleLike: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentLikeResponse"];
                };
            };
        };
    };
    OrdersController_estimate: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 주문·전이 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderEstimateResponse"];
                };
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 주문·전이 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    OrdersController_listMine: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                /** @description 현재 멤버의 publicId — 주문·전이 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrdersResponse"];
                };
            };
        };
    };
    OrdersController_transition: {
        parameters: {
            query?: never;
            header?: {
                /** @description 현재 멤버의 publicId — 주문·전이 요청에 필요 (D-017) */
                "X-Member-Id"?: string;
            };
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    AdminOrdersController_listAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
                clubId?: string;
                q?: string;
                from?: string;
                to?: string;
                actionRequired?: boolean;
                ids?: string[];
                sort?: "latest" | "oldest" | "changed_latest" | "changed_oldest";
                scope?: "selected" | "page";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminOrdersResponse"];
                };
            };
        };
    };
    AdminOrdersController_csv: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "RECEIVED" | "CONFIRMED" | "IN_PRODUCTION" | "PRODUCED" | "SHIPPED" | "DELIVERED" | "PURCHASE_CONFIRMED" | "CANCELED" | "REFUND_REQUESTED" | "REFUNDED" | "REMAKE_REQUESTED";
                clubId?: string;
                q?: string;
                from?: string;
                to?: string;
                actionRequired?: boolean;
                ids?: string[];
                sort?: "latest" | "oldest" | "changed_latest" | "changed_oldest";
                scope?: "selected" | "page";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 주문 전체 CSV (BOM 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    AdminOrdersController_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTransitionOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    AdminOrdersController_bulkTransition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminBulkTransitionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminOrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    AdminOrdersController_checkProduction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductionCheckResponse"];
                };
            };
        };
    };
    AdminOrdersController_dispatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDispatchDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    AdminOrdersController_receiveVendorEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminVendorEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderResponse"];
                };
            };
        };
    };
    AdminClubsController_findAll: {
        parameters: {
            query?: {
                q?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClubResponse"][];
                };
            };
        };
    };
    AdminClubsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClubDetailResponse"];
                };
            };
        };
    };
    AdminClubsController_updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminNoteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNoteResponse"];
                };
            };
        };
    };
    AdminMembersController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                clubId?: string;
                q?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminMembersResponse"];
                };
            };
        };
    };
    AdminMembersController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMemberDetailResponse"];
                };
            };
        };
    };
    AdminMembersController_updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminNoteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNoteResponse"];
                };
            };
        };
    };
}
