/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/clubs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ClubsController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/clubs/{clubId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ClubsController_findMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/clubs/{clubId}/books': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BooksController_list'];
    put?: never;
    post: operations['BooksController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/{bookId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BooksController_detail'];
    put?: never;
    post?: never;
    delete: operations['BooksController_remove'];
    options?: never;
    head?: never;
    patch: operations['BooksController_update'];
    trace?: never;
  };
  '/api/books/{bookId}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommentsController_list'];
    put?: never;
    post: operations['CommentsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/comments/{commentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['CommentsController_remove'];
    options?: never;
    head?: never;
    patch: operations['CommentsController_update'];
    trace?: never;
  };
  '/api/comments/{commentId}/like': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommentsController_toggleLike'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ClubResponse: {
      publicId: string;
      name: string;
      description: string;
      memberCount: number;
      /** Format: date-time */
      createdAt: string;
    };
    ClubMemberResponse: {
      /** @enum {string} */
      role: 'LEADER' | 'MEMBER';
      publicId: string;
      name: string;
      avatarEmoji: string;
      color: string;
      /** Format: date-time */
      joinedAt: string;
    };
    MemberSummaryResponse: {
      publicId: string;
      name: string;
      avatarEmoji: string;
      color: string;
    };
    BookResponse: {
      /** @enum {string} */
      status: 'UPCOMING' | 'READING' | 'DONE';
      publicId: string;
      title: string;
      author: string;
      publisher: string | null;
      coverColor: string;
      coverEmoji: string;
      /** Format: date-time */
      meetingDate: string | null;
      /** Format: date-time */
      periodFrom: string | null;
      /** Format: date-time */
      periodTo: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      participants: components['schemas']['MemberSummaryResponse'][];
      commentCount: number;
    };
    PageMetaResponse: {
      page: number;
      limit: number;
      totalCount: number;
      hasNext: boolean;
    };
    PaginatedBooksResponse: {
      items: components['schemas']['BookResponse'][];
      meta: components['schemas']['PageMetaResponse'];
    };
    CreateBookDto: {
      title: string;
      author: string;
      publisher?: string | null;
      coverColor: string;
      coverEmoji: string;
      /** @enum {string} */
      status?: 'UPCOMING' | 'READING' | 'DONE';
      meetingDate?: string | null;
      periodFrom?: string | null;
      periodTo?: string | null;
      participantIds?: string[];
    };
    UpdateBookDto: {
      title?: string;
      author?: string;
      publisher?: string | null;
      coverColor?: string;
      coverEmoji?: string;
      /** @enum {string} */
      status?: 'UPCOMING' | 'READING' | 'DONE';
      meetingDate?: string | null;
      periodFrom?: string | null;
      periodTo?: string | null;
      participantIds?: string[];
    };
    DeletedResponse: {
      publicId: string;
      deleted: boolean;
    };
    CommentResponse: {
      publicId: string;
      deleted: boolean;
      member: components['schemas']['MemberSummaryResponse'] | null;
      page: number | null;
      quote: string | null;
      content: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string | null;
      isEdited: boolean;
      likeCount: number;
      likedByMe: boolean;
    };
    CommentThreadResponse: {
      replies: components['schemas']['CommentResponse'][];
      publicId: string;
      deleted: boolean;
      member: components['schemas']['MemberSummaryResponse'] | null;
      page: number | null;
      quote: string | null;
      content: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string | null;
      isEdited: boolean;
      likeCount: number;
      likedByMe: boolean;
    };
    PaginatedCommentsResponse: {
      items: components['schemas']['CommentThreadResponse'][];
      meta: components['schemas']['PageMetaResponse'];
    };
    CreateCommentDto: {
      content: string;
      page?: number | null;
      quote?: string | null;
      parentId?: string;
    };
    UpdateCommentDto: {
      content?: string;
      page?: number | null;
      quote?: string | null;
    };
    CommentLikeResponse: {
      liked: boolean;
      likeCount: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ClubsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClubResponse'][];
        };
      };
    };
  };
  ClubsController_findMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        clubId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClubMemberResponse'][];
        };
      };
    };
  };
  BooksController_list: {
    parameters: {
      query?: {
        status?: 'UPCOMING' | 'READING' | 'DONE';
        page?: number;
        limit?: number;
      };
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        clubId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedBooksResponse'];
        };
      };
    };
  };
  BooksController_create: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        clubId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBookDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookResponse'];
        };
      };
    };
  };
  BooksController_detail: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        bookId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookResponse'];
        };
      };
    };
  };
  BooksController_remove: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        bookId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletedResponse'];
        };
      };
    };
  };
  BooksController_update: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        bookId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBookDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookResponse'];
        };
      };
    };
  };
  CommentsController_list: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
      };
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        bookId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedCommentsResponse'];
        };
      };
    };
  };
  CommentsController_create: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        bookId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCommentDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentResponse'];
        };
      };
    };
  };
  CommentsController_remove: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletedResponse'];
        };
      };
    };
  };
  CommentsController_update: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        commentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCommentDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentResponse'];
        };
      };
    };
  };
  CommentsController_toggleLike: {
    parameters: {
      query?: never;
      header?: {
        /** @description 현재 멤버의 publicId — 쓰기 요청에 필요 (D-017) */
        'X-Member-Id'?: string;
      };
      path: {
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentLikeResponse'];
        };
      };
    };
  };
}
